apiVersion: v1
kind: ServiceAccount
metadata:
  name: leaderelection-sa
  namespace: cybericebox
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: leaderelection-role
  namespace: cybericebox
rules:
  - apiGroups:
      - ""
      - "core"
      - "apps"
      - "projectcalico.org"
      - "networking.k8s.io"
      - "metrics.k8s.io/v1beta1"
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: leaderelection-rolebinding
  namespace: cybericebox
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: leaderelection-role
subjects:
  - kind: ServiceAccount
    name: leaderelection-sa
    namespace: cybericebox