apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  namespace: cybericebox
  labels:
    app: agent
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      name: agent
      namespace: cybericebox
      labels:
        app: agent
    spec:
      automountServiceAccountToken: true
      serviceAccountName: leaderelection-sa
      containers:
        - name: agent
          image: cybericebox/agent:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: config
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"