// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.0
// source: agent.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Agent_Ping_FullMethodName                 = "/agent.Agent/Ping"
	Agent_GetLabs_FullMethodName              = "/agent.Agent/GetLabs"
	Agent_CreateLabs_FullMethodName           = "/agent.Agent/CreateLabs"
	Agent_DeleteLabs_FullMethodName           = "/agent.Agent/DeleteLabs"
	Agent_StopLabs_FullMethodName             = "/agent.Agent/StopLabs"
	Agent_StartLabs_FullMethodName            = "/agent.Agent/StartLabs"
	Agent_AddLabChallenges_FullMethodName     = "/agent.Agent/AddLabChallenges"
	Agent_DeleteLabsChallenges_FullMethodName = "/agent.Agent/DeleteLabsChallenges"
	Agent_StartLabsChallenges_FullMethodName  = "/agent.Agent/StartLabsChallenges"
	Agent_StopLabsChallenges_FullMethodName   = "/agent.Agent/StopLabsChallenges"
	Agent_ResetLabsChallenges_FullMethodName  = "/agent.Agent/ResetLabsChallenges"
)

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentClient interface {
	// metrics
	Ping(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// laboratory
	GetLabs(ctx context.Context, in *LabsRequest, opts ...grpc.CallOption) (*GetLabsResponse, error)
	CreateLabs(ctx context.Context, in *CreateLabsRequest, opts ...grpc.CallOption) (*CreateLabsResponse, error)
	DeleteLabs(ctx context.Context, in *LabsRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	StopLabs(ctx context.Context, in *LabsRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	StartLabs(ctx context.Context, in *LabsRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// challenge
	AddLabChallenges(ctx context.Context, in *AddLabChallengesRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	DeleteLabsChallenges(ctx context.Context, in *LabsChallengesRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	StartLabsChallenges(ctx context.Context, in *LabsChallengesRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	StopLabsChallenges(ctx context.Context, in *LabsChallengesRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	ResetLabsChallenges(ctx context.Context, in *LabsChallengesRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type agentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClient(cc grpc.ClientConnInterface) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) Ping(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, Agent_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) GetLabs(ctx context.Context, in *LabsRequest, opts ...grpc.CallOption) (*GetLabsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLabsResponse)
	err := c.cc.Invoke(ctx, Agent_GetLabs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) CreateLabs(ctx context.Context, in *CreateLabsRequest, opts ...grpc.CallOption) (*CreateLabsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLabsResponse)
	err := c.cc.Invoke(ctx, Agent_CreateLabs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) DeleteLabs(ctx context.Context, in *LabsRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, Agent_DeleteLabs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) StopLabs(ctx context.Context, in *LabsRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, Agent_StopLabs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) StartLabs(ctx context.Context, in *LabsRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, Agent_StartLabs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) AddLabChallenges(ctx context.Context, in *AddLabChallengesRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, Agent_AddLabChallenges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) DeleteLabsChallenges(ctx context.Context, in *LabsChallengesRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, Agent_DeleteLabsChallenges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) StartLabsChallenges(ctx context.Context, in *LabsChallengesRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, Agent_StartLabsChallenges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) StopLabsChallenges(ctx context.Context, in *LabsChallengesRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, Agent_StopLabsChallenges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ResetLabsChallenges(ctx context.Context, in *LabsChallengesRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, Agent_ResetLabsChallenges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
// All implementations must embed UnimplementedAgentServer
// for forward compatibility
type AgentServer interface {
	// metrics
	Ping(context.Context, *EmptyRequest) (*EmptyResponse, error)
	// laboratory
	GetLabs(context.Context, *LabsRequest) (*GetLabsResponse, error)
	CreateLabs(context.Context, *CreateLabsRequest) (*CreateLabsResponse, error)
	DeleteLabs(context.Context, *LabsRequest) (*EmptyResponse, error)
	StopLabs(context.Context, *LabsRequest) (*EmptyResponse, error)
	StartLabs(context.Context, *LabsRequest) (*EmptyResponse, error)
	// challenge
	AddLabChallenges(context.Context, *AddLabChallengesRequest) (*EmptyResponse, error)
	DeleteLabsChallenges(context.Context, *LabsChallengesRequest) (*EmptyResponse, error)
	StartLabsChallenges(context.Context, *LabsChallengesRequest) (*EmptyResponse, error)
	StopLabsChallenges(context.Context, *LabsChallengesRequest) (*EmptyResponse, error)
	ResetLabsChallenges(context.Context, *LabsChallengesRequest) (*EmptyResponse, error)
	mustEmbedUnimplementedAgentServer()
}

// UnimplementedAgentServer must be embedded to have forward compatible implementations.
type UnimplementedAgentServer struct {
}

func (UnimplementedAgentServer) Ping(context.Context, *EmptyRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAgentServer) GetLabs(context.Context, *LabsRequest) (*GetLabsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLabs not implemented")
}
func (UnimplementedAgentServer) CreateLabs(context.Context, *CreateLabsRequest) (*CreateLabsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLabs not implemented")
}
func (UnimplementedAgentServer) DeleteLabs(context.Context, *LabsRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLabs not implemented")
}
func (UnimplementedAgentServer) StopLabs(context.Context, *LabsRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopLabs not implemented")
}
func (UnimplementedAgentServer) StartLabs(context.Context, *LabsRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartLabs not implemented")
}
func (UnimplementedAgentServer) AddLabChallenges(context.Context, *AddLabChallengesRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLabChallenges not implemented")
}
func (UnimplementedAgentServer) DeleteLabsChallenges(context.Context, *LabsChallengesRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLabsChallenges not implemented")
}
func (UnimplementedAgentServer) StartLabsChallenges(context.Context, *LabsChallengesRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartLabsChallenges not implemented")
}
func (UnimplementedAgentServer) StopLabsChallenges(context.Context, *LabsChallengesRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopLabsChallenges not implemented")
}
func (UnimplementedAgentServer) ResetLabsChallenges(context.Context, *LabsChallengesRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetLabsChallenges not implemented")
}
func (UnimplementedAgentServer) mustEmbedUnimplementedAgentServer() {}

// UnsafeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServer will
// result in compilation errors.
type UnsafeAgentServer interface {
	mustEmbedUnimplementedAgentServer()
}

func RegisterAgentServer(s grpc.ServiceRegistrar, srv AgentServer) {
	s.RegisterService(&Agent_ServiceDesc, srv)
}

func _Agent_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Ping(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_GetLabs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LabsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetLabs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_GetLabs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetLabs(ctx, req.(*LabsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_CreateLabs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLabsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).CreateLabs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_CreateLabs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).CreateLabs(ctx, req.(*CreateLabsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_DeleteLabs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LabsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).DeleteLabs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_DeleteLabs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).DeleteLabs(ctx, req.(*LabsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_StopLabs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LabsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).StopLabs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_StopLabs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).StopLabs(ctx, req.(*LabsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_StartLabs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LabsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).StartLabs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_StartLabs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).StartLabs(ctx, req.(*LabsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_AddLabChallenges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLabChallengesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).AddLabChallenges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_AddLabChallenges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).AddLabChallenges(ctx, req.(*AddLabChallengesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_DeleteLabsChallenges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LabsChallengesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).DeleteLabsChallenges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_DeleteLabsChallenges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).DeleteLabsChallenges(ctx, req.(*LabsChallengesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_StartLabsChallenges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LabsChallengesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).StartLabsChallenges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_StartLabsChallenges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).StartLabsChallenges(ctx, req.(*LabsChallengesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_StopLabsChallenges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LabsChallengesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).StopLabsChallenges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_StopLabsChallenges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).StopLabsChallenges(ctx, req.(*LabsChallengesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ResetLabsChallenges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LabsChallengesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ResetLabsChallenges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ResetLabsChallenges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ResetLabsChallenges(ctx, req.(*LabsChallengesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Agent_ServiceDesc is the grpc.ServiceDesc for Agent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Agent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Agent_Ping_Handler,
		},
		{
			MethodName: "GetLabs",
			Handler:    _Agent_GetLabs_Handler,
		},
		{
			MethodName: "CreateLabs",
			Handler:    _Agent_CreateLabs_Handler,
		},
		{
			MethodName: "DeleteLabs",
			Handler:    _Agent_DeleteLabs_Handler,
		},
		{
			MethodName: "StopLabs",
			Handler:    _Agent_StopLabs_Handler,
		},
		{
			MethodName: "StartLabs",
			Handler:    _Agent_StartLabs_Handler,
		},
		{
			MethodName: "AddLabChallenges",
			Handler:    _Agent_AddLabChallenges_Handler,
		},
		{
			MethodName: "DeleteLabsChallenges",
			Handler:    _Agent_DeleteLabsChallenges_Handler,
		},
		{
			MethodName: "StartLabsChallenges",
			Handler:    _Agent_StartLabsChallenges_Handler,
		},
		{
			MethodName: "StopLabsChallenges",
			Handler:    _Agent_StopLabsChallenges_Handler,
		},
		{
			MethodName: "ResetLabsChallenges",
			Handler:    _Agent_ResetLabsChallenges_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}
