// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import (
	"context"

	"github.com/gofrs/uuid"
)

type Querier interface {
	CreateLaboratory(ctx context.Context, arg CreateLaboratoryParams) error
	DeleteLaboratory(ctx context.Context, id uuid.UUID) (int64, error)
	GetLaboratories(ctx context.Context) ([]Laboratory, error)
}

var _ Querier = (*Queries)(nil)
